name       : libcompizconfig
version    : 0.8.16
release    : 2
source     :
    - https://gitlab.com/compiz/libcompizconfig/-/archive/v0.8.16/libcompizconfig-v0.8.16.tar.bz2 : c08ad534ace9bab87c618ffc03f12d3dcc32a41bd173349ae7ef573ff76339fc
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : CompizConfig plugin required for compizconfig-settings-manager.
description: |
    CompizConfig plugin required for compizconfig-settings-manager.
builddeps  :
    - pkgconfig(compiz)
    - pkgconfig(gl)
    - pkgconfig(protobuf)
    - pkgconfig(x11)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
