name       : libcompizconfig
version    : 0.8.18
release    : 7
source     :
    - https://gitlab.com/compiz/libcompizconfig/-/archive/v0.8.18/libcompizconfig-v0.8.18.tar.bz2 : b18f733e7f52bbbf10170b09e2cd41ea324376bf4af9b103514602f2647046cd
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.mate
summary    : CompizConfig plugin required for compizconfig-settings-manager
description: |
    CompizConfig plugin required for compizconfig-settings-manager.
builddeps  :
    - pkgconfig(compiz)
    - pkgconfig(gl)
    - pkgconfig(protobuf)
    - pkgconfig(x11)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
